// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	scalar "github.com/s-ichikawa/piql/scalar"
)

type CallWebhook struct {
	Username   string `json:"username"`
	HashString string `json:"hashString"`
}

type DecrementPixel struct {
	Username string `json:"username"`
	ID       string `json:"id"`
}

type DeleteGraph struct {
	Username string `json:"username"`
	ID       string `json:"id"`
}

type DeletePixel struct {
	Username string `json:"username"`
	ID       string `json:"id"`
	Date     string `json:"date"`
}

type DeleteUser struct {
	Username string `json:"username"`
}

type DeleteWebhook struct {
	Username   string `json:"username"`
	HashString string `json:"hashString"`
}

type GetGraph struct {
	Username string  `json:"username"`
	ID       string  `json:"id"`
	Date     *string `json:"date"`
	Mode     *string `json:"mode"`
}

type GetGraphs struct {
	Username string `json:"username"`
}

type GetPixel struct {
	Username string `json:"username"`
	ID       string `json:"id"`
	Date     string `json:"date"`
}

type GetWebhooks struct {
	Username string `json:"username"`
}

type IncrementPixel struct {
	Username string `json:"username"`
	ID       string `json:"id"`
}

type NewGraph struct {
	Username string `json:"username"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Unit     string `json:"unit"`
	Type     string `json:"type"`
	Color    string `json:"color"`
}

type NewPixel struct {
	Username string          `json:"username"`
	ID       string          `json:"id"`
	Date     string          `json:"date"`
	Quantity scalar.Quantity `json:"quantity"`
}

type NewToken struct {
	Username string `json:"username"`
	NewToken string `json:"newToken"`
}

type NewUser struct {
	Token               string `json:"token"`
	Username            string `json:"username"`
	AgreeTermsOfService string `json:"agreeTermsOfService"`
	NotMinor            string `json:"notMinor"`
}

type NewWebhook struct {
	Username string `json:"username"`
	GraphID  string `json:"graphID"`
	Type     string `json:"type"`
}

type NewWebhookResponse struct {
	HashString *string `json:"hashString"`
	Message    string  `json:"message"`
	IsSuccess  bool    `json:"isSuccess"`
}

type UpdateGraph struct {
	Username string `json:"username"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Unit     string `json:"unit"`
	Color    string `json:"color"`
}
